print("-----------------------INICIANDO----------------------------")
print("Seja bem vindo(a), vamos calcular a media do aluno.")
nm = input("Qual o nome do aluno?")
nt1 = float(input('Ok, agora me diga a primeira nota do aluno.'))
nt2 =  float(input('Agora a segunda.'))
nt3 =  float(input('Agora a terceira.'))
nt4 =  float(input('Agora a quarta.'))
soma =  float(nt1 + nt2 + nt3 + nt4)
calcmedia = round((soma/4), 1)
print("-----------------------MEDIA CALCULADA-----------------------")
print("A media do aluno {} é igual a {}.".format(nm, calcmedia))
print("-----------------------FIM DE CÓDIGO-------------------------")